#!/bin/bash
# scripts/update-blog.sh
# 自动同步 blog submodule 的变更

set -e  # 遇到错误立即退出

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BLOG_DIR="$PROJECT_ROOT/blog"

echo "🔄 开始同步 blog submodule..."

# 1. 检查 blog 目录是否存在
if [ ! -d "$BLOG_DIR" ]; then
  echo "❌ 错误：blog 目录不存在"
  echo "💡 请先运行：git submodule update --init --recursive"
  exit 1
fi

# 2. 进入 blog 目录
cd "$BLOG_DIR"

# 3. 检查是否有变更（包括未跟踪的文件）
if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "✅ 没有需要提交的变更"
  exit 0
fi

# 4. 显示变更
echo "📝 检测到以下变更："
git status --short

# 5. 添加所有变更
git add .

# 6. 提交变更
COMMIT_MSG="Auto: Update articles from post_waver

Generated by: post_waver tools
Date: $(date '+%Y-%m-%d %H:%M:%S')"

git commit -m "$COMMIT_MSG"

# 7. 推送到远程
echo "📤 推送到 CharliesBlogs 仓库..."
git push origin main

# 8. 返回项目根目录
cd "$PROJECT_ROOT"

# 9. 更新 submodule 引用
echo "🔄 更新 post_waver 的 submodule 引用..."
git add blog
git commit -m "Auto: Update blog submodule reference"

echo "✅ Blog submodule 同步完成！"
