#!/bin/bash
# scripts/update-blog.sh
# 自动同步 blog/ 目录的变更到远程仓库

set -e  # 遇到错误立即退出

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BLOG_DIR="$PROJECT_ROOT/blog"

echo "🔄 开始同步 blog 目录..."

# 1. 检查 blog 目录是否存在
if [ ! -d "$BLOG_DIR" ]; then
  echo "❌ 错误：blog 目录不存在"
  echo "💡 请先初始化 Hexo 博客："
  echo "   1. 使用现有博客: ln -s /path/to/blog ./blog"
  echo "   2. 初始化新博客: hexo init blog && cd blog && pnpm install"
  exit 1
fi

# 2. 检查 blog 是否是 git 仓库
if [ ! -d "$BLOG_DIR/.git" ]; then
  echo "⚠️  警告：blog 目录不是 git 仓库"
  echo "💡 如果需要版本控制，请先初始化："
  echo "   cd blog && git init"
  exit 0
fi

# 3. 进入 blog 目录
cd "$BLOG_DIR"

# 4. 检查是否有变更（包括未跟踪的文件）
if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
  echo "✅ 没有需要提交的变更"
  exit 0
fi

# 5. 显示变更
echo "📝 检测到以下变更："
git status --short

# 6. 添加所有变更
git add .

# 7. 提交变更
COMMIT_MSG="Auto: Update articles from post_waver

Generated by: post_waver tools
Date: $(date '+%Y-%m-%d %H:%M:%S')"

git commit -m "$COMMIT_MSG"

# 8. 推送到远程（如果配置了）
if git remote get-url origin &>/dev/null; then
  echo "📤 推送到 blog 远程仓库..."
  git push origin main
else
  echo "⚠️  blog 未配置远程仓库，跳过推送"
  echo "💡 如需远程备份，请先添加："
  echo "   cd blog && git remote add origin <your-repo-url>"
fi

echo "✅ Blog 同步完成！"

